### ISSUE TITLE
Criar models básicos

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/django-cards#1]
Model de Card. Campos esperados:
- título (obrigatório)
- texto (obrigatório) (HTML)
- eixo (categoria) (lista pré-determinada de valores)
- público (lista pré-determinada de valores)
- galeria de imagens (pode ser um array de URLs ou um relacionamento com um model dedicado para cada foto)
- autor (usuário que criou o card)
- autores (lista de objetos com titulo e campo de texto HTML) (pode ser um relacionamento com outro modelo  também)
- vídeos (embeds do Youtube) (pode ser mais de um)
- tags (possivelmente, um relacionamento com um model Tag seja mais apropriado)
- gostei (lista dos usuários que curtiram o card. ManytoMany pode ser o melhor caminho)
- você vai precisar de (texto HTML)
- desenvolvimento (texto HTML)
- para saber mais (texto HTML)
- dica (texto HTML)
- certificada (marca se esse card foi certificado ou não)

**Comment by tiagofassoni** [comment]
eixos e público são hard-coded nos modelos ou colocados no admin?

**Comment by laurybueno** [comment]
Via admin

**Comment by laurybueno** [comment]
Quero lembrar aqui que o requisito de acesso por contratos explicado na #2 pode exigir que o model de Card tenha uma foreign key para Contract.

**Comment by tiagofassoni** [comment]
bom saber. Valeu!

**Comment by tiagofassoni** [comment]
Coisas de nomenclatura, porque é em inglês esse treco:

- 'Eixo' deixei como 'axis'
- 'Público' deixei como 'audience'. 'Public' em geral é usado na dicotomia público/privado. Outro jeito é 'intended_audience'
- Qualquer coisa que envolva arrays estou modelando como um modelo separado, porque array tem no Postgresql, mas não tem no SQLite nem no MySQL. 
- Para o campo 'author', uso uma referencia ao timtec user model ou ao user model em si?

**Comment by tiagofassoni** [comment]
- [x] título
- [x] texto
- [x] eixo
- [x] público
- [x] galeria de imagens
- [x] autor
- [x] autores
- [x] vídeos
- [x] tags
- [x] gostei
- [x] você vai precisar de
- [x] desenvolvimento
- [x] para saber mais
- [x] dica
- [x] certificada

**Comment by laurybueno** [comment]
OK para todas as traduções que vc propôs e para a decisão de usar modelos em vez de arryas.

Author deve linkar da seguinte forma:
```python
from django.conf import settings

class MyModel(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Author'))
```

**Comment by tiagofassoni** [comment]
Valeu!


On 7 August 2017 at 16:56:34, Laury Bueno (notifications@github.com) wrote:

OK para todas as traduções que vc propôs e para a decisão de usar modelos
em vez de arryas.

Author deve linkar da seguinte forma:

from django.conf import settings

class MyModel(models.Model):
author = models.ForeignKey(settings.AUTH_USER_MODEL,
verbose_name=_('User'), blank=True, null=True)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/hacklabr/django-cards/issues/1#issuecomment-320763899>,
or mute the thread

**Comment by laurybueno** [comment]
O meu código é mais um exemplo mesmo, mas já deu pra ter uma ideia de como pegar o modelo de usuário
