### ISSUE TITLE
Serializer e View que permitam criar, ler e editar cards via Rest Framework

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/django-cards#2]
Deverá cuidar o upload de imagens para a galeria.

Controles de acesso:
- cards só podem ser editadas e apagados por autores ou por membros de grupos pré-determinados em uma variável no settings.py (DJANGO_CARDS_ADMIN_GROUPS)
- cards que foram certificados não podem mais ser editadas ou apagados por seu autor original. Apenas os membros dos grupos mencionados acima que poderão fazer mudanças 
- usuários só podem acessar práticas não certificadas que tenham sido criadas por usuários do mesmo contrato ([modelo Contract do pacote paralapraca](https://github.com/hacklabr/paralapraca/blob/master/paralapraca/models.py#L15) tem uma lista de grupos do  django que contêm os usuários que pertencem a cada contrato)
- usuários podem ler todas as práticas certificadas independentemente da relação com contratos

Filtros necessários:
- certificação de card (cada card pode estar ou não estar certificado)
- busca textual para todos os campos que permitem HTML e para o Título
- busca por tags
- busca por eixo (categoria)

**Comment by laurybueno** [comment]
@tiagofassoni uma coisa importante que está naquele documento de escopo do assim se faz, mas não está refletida/traduzida aqui é a seguinte: usuários do grupo Espaço Aberto não podem criar cards. Talvez, a melhor forma de implementar isso seja ter uma variável nos settings que diz quais grupos têm direito de criar cards novos.

**Comment by tiagofassoni** [comment]
De leitura:

- [x] Ler todos
- [x] Implementar o Contract como restrição para ler todos
- [x] Busca por cards certificados
- [x] Busca por tags (coloquei o tagulous, YOLO) - tagulous não rolou, foi django-taggit
- [x] Busca FTS em todos os campos que permitam
- [x] Busca por eixo (categoria) - ainda tô pensando que isso 

Escrita:
- [x] Criar card (qualquer um consegue, aqui é várzea)
- [] Filtro de controle de criar card.

Update - Partial Update nao vai rolar. Mas Update vai:
- [x] Update tá rolando
- [ ] Miríade de controles de update
- [ ] Controle de acesso por grupos (e tenho fortes dúvidas de que o settings.py seja a melhor ideia - talvez fazer um grupo)

**Comment by laurybueno** [comment]
@tiagofassoni segura a onda um pouco, mestre:
- criar card não é coisa que todo mundo pode. Olha o meu [comentário anterior](https://github.com/hacklabr/django-cards/issues/2#issuecomment-320779155) nesta issue. 
- a questão do controle de accesso por grupos de contratos não é feita pelo settings, é feita pelos grupos ligados a cada Contract (veja o terceiro item [deste comentário](https://github.com/hacklabr/django-cards/issues/2#issue-246899231))

**Comment by tiagofassoni** [comment]
Mais coisa dos serializers:

- [x] Escrever (e updatear) todos os campos simples de foreignkey (audience, authors, axis, youtubeembed)
- [ ] Escrever (e updatear) galeria de imagens - Falta Testar
- [ ] Montar um viewset só para likes
- [ ]

**Comment by tiagofassoni** [comment]
Estou subindo no develop as mudanças já feitas.

Em particular, filtrar por contracts é MUITO custoso. Vai ser bem pesado em produção.
