### ISSUE TITLE
Tags - fazer na mão ou usar biblioteca?

### ISSUE THREAD

**Issue by tiagofassoni** [hacklabr/django-cards#4]
A mais fácil que achei (em termos de integrar fácil com o resto do django) foi esta aqui:

http://radiac.net/projects/django-tagulous/documentation/parser/

Me parece algo muito útil para os forms no angular (e até para modelar vários tipos de foreignkey). Mas deixo essa decisão com o pessoal que vai fazer o frontend

**Comment by tiagofassoni** [comment]
@laurybueno

**Comment by laurybueno** [comment]
Essa lib é só parser mesmo? Parece bacana. Podemos usar se não for afetar os models do Django (provavelmente é bacana existir um model de tag com relacionamento via chaves estrangeiras)

**Comment by tiagofassoni** [comment]
Não é só parser não. Ela existe também (e principalmente) no nível de modelo


On 7 August 2017 at 16:52:17, Laury Bueno (notifications@github.com) wrote:

Essa lib é só parser mesmo? Parece bacana. Podemos usar se não for afetar
os models do Django (provavelmente é bacana existir um model de tag com
relacionamento via chaves estrangeiras)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hacklabr/django-cards/issues/4#issuecomment-320762852>,
or mute the thread

**Comment by laurybueno** [comment]
Entendi.

Mas ainda não tá claro pra mim como ela recebe o texto das tags. O Angular mandaria as tags em um string separada por vírgulas mesmo? (se sim, é bem bacana).

O que me preocupa é poder reproduzir a funcionalidade de tags que já existe no fórum hoje para o usuário. Nós usamos esse campo lá: https://angular-ui.github.io/ui-select/demo-select2-with-bootstrap.html

**Comment by tiagofassoni** [comment]
fui ver, o angular pode mandar as tags em uma string separada com virgulas e tudo sucesso
